# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-12 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('movile', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('mensaje', models.CharField(max_length=200)),
            ],
        ),
    ]
